#!/bin/bash -e
# animation 0.0.3
# Copyright (C) 2018 Ryuichi Ueda
# GPLv3 is applied to this script

### USAGE ###
[ "$1" = "-h" ] &&
echo 'usage: animation [-l <lines>] [-d <delay>] [-f <font>]' &&
exit 0

### PROCEDURE AT END ###
trap 'rm -f /tmp/*.$$.png' EXIT

### DEFAULT PARAMETERS AND OPTION PROCESSING ###
delay=50
lines=1
font="VL-Gothic-Regular"

while [ "$#" -gt 0 ] ; do
	[ "$1" = "-d" ] && shift && delay="$(tr -dc '0-9' <<< $1)"
	[ "$1" = "-l" ] && shift && lines="$(tr -dc '0-9' <<< $1)"
	[ "$1" = "-f" ] && shift && font="$(tr -dc '0-9A-Za-z-' <<< $1)"
	shift
done

conv(){
	num=$(printf "%03d" "$2")
	convert -font "$font" -pointsize 60 \
		-background black \
		-fill white "label:$1" "/tmp/$num.$$.png"
}

n=0
tmp=""
while read line ; do
	n=$((n + 1))
	[ "$n" -gt 100 ] && break

	if [ "$((n%lines))" -eq 0 ] ; then
		conv "${out}${line}" "$n"
		out=""
	else
		out="${out}${line}\\n"
	fi
	tmp="$out"
done

### OUTPUT REMAINING LINES ###
[ -n "$tmp" ] && conv "$tmp" "$n"

convert  -delay "$delay" /tmp/*.$$.png /images/animation.gif
