#!/bin/bash
# imgout 0.0.1 
# Copyright (C) 2018 Ryuichi Ueda
# GPLv3 is applied to this script

### USAGE ###
[ "$1" = "-h" ] &&
echo 'usage: imgout [-f <font>]' &&
exit 0

font="VL-Gothic-Regular"

while [ "$#" -gt 0 ] ; do
	[ "$1" = "-f" ] && shift && font="$(tr -dc '0-9A-Za-z-' <<< $1)"
	shift
done

convert -font "$font" -pointsize 60 -background black \
	-fill white "label:$(sed 's;\\;\\\\;g' /dev/stdin)" "/images/tmp.png"
